# 开发环境配置
server:
  port: 8300                # HTTP 端口
  servlet:
    context-path: /         # 应用的访问路径
  max-http-request-header-size: 20MB
  tomcat:
    uri-encoding: UTF-8     # tomcat的URI编码
    accept-count: 200       # 连接数满后的排队数，默认为100
    threads:
      max: 200              # tomcat最大线程数，默认为200
      min-spare: 20         # Tomcat启动初始化的线程数，默认值10
    connection-timeout: 30s
    max-http-response-header-size: 2MB


# Spring 配置
spring:
  profiles:
    active: dev