# 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pt_tools?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: pt-tools
    password: pt-tools-password2023

  devtools:
    restart:
      # 热部署开关  线上记得关闭
      enabled: false

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:com/derrors/pt/tools/data/**/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto                     # 主键类型
      logic-delete-field: is_deleted    # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

# 日志配置
logging:
  level:
    com.derrors: info
    org.springframework: info
  file:
    path: logs